$(document).ready(function(){
    $("#y1").click(function(){
        $("#t1").hide();
    });
    $("#y1").click(function(){
        $("#t2").show();
    });
	$("#n1").click(function(){
        $("#t1").hide();
    });
    $("#n1").click(function(){
        alert("You cant donate blood");
    });
	$("#y2").click(function(){
        $("#t2").hide();
    });
    $("#y2").click(function(){
        $("#t3").show();
    });
	$("#n2").click(function(){
        $("#t2").hide();
    });
    $("#n2").click(function(){
        $("#t4").show();
    });
	$("#y3").click(function(){
        $("#t3").hide();
    });
    $("#y3").click(function(){
        alert("Sorry! You cant donate the blood")
    });
	$("#n3").click(function(){
        $("#t3").hide();
    });
    $("#n3").click(function(){
        $("#t4").show();
    });
	$("#y4").click(function(){
        $("#t4").hide();
    });
    $("#y4").click(function(){
        alert("Sorry! You cant donate the blood for 1 year")
    });
	$("#n4").click(function(){
        $("#t4").hide();
    });
    $("#n4").click(function(){
        $("#t5").show();
    });
	$("#y5").click(function(){
        $("#t5").hide();
    });
    $("#y5").click(function(){
        alert("Cant donate blood for 10 days")
    });
	$("#n5").click(function(){
        $("#t5").hide();
    });
    $("#n5").click(function(){
        $("#t6").show();
    });

	$("#y6").click(function(){
        $("#t6").hide();
    });
    $("#y6").click(function(){
        alert("Cant donate blood for 10 days")
    });
	$("#n6").click(function(){
        $("#t6").hide();
    });
    $("#n6").click(function(){
        $("#t7").show();
    });
	$("#y7").click(function(){
        $("#t7").hide();
    });
    $("#y7").click(function(){
        alert("Cant donate blood")
    });
	$("#n7").click(function(){
        $("#t7").hide();
    });
    $("#n7").click(function(){
        $("#t8").show();
    });
	$("#y8").click(function(){
        $("#t8").hide();
    });
    $("#y8").click(function(){
        alert("Cant donate blood")
    });
	$("#n8").click(function(){
        $("#t8").hide();
    });
    $("#n8").click(function(){
        $("#t9").show();
    });
	$("#y9").click(function(){
        $("#t9").hide();
    });
    $("#y9").click(function(){
        alert("Cant donate blood for 10 days")
    });
	$("#n9").click(function(){
        $("#t9").hide();
    });
    $("#n9").click(function(){
        $("#t10").show();
    });
	$("#y10").click(function(){
        $("#t10").hide();
    });
    $("#y10").click(function(){
        alert("Cant donate blood for 10 days")
    });
	$("#n10").click(function(){
        $("#t10").hide();
    });
    $("#n10").click(function(){
        $("#t11").show();
    });
	$("#y11").click(function(){
        $("#t11").hide();
    });
    $("#y11").click(function(){
        alert("Cant donate blood for 10 days")
    });
	$("#n11").click(function(){
        $("#t11").hide();
    });
    $("#n11").click(function(){
        $("#t12").show();
    });
	$("#y12").click(function(){
        $("#t12").hide();
    });
    $("#y12").click(function(){
        alert("Cant donate blood for 10 days")
    });
	$("#n12").click(function(){
        $("#t12").hide();
    });
    $("#n12").click(function(){
        $("#t13").show();
    });
	$("#y13").click(function(){
        $("#t13").hide();
    });
    $("#y13").click(function(){
        alert("Cant donate blood for 10 days")
    });
	$("#n13").click(function(){
        $("#t13").hide();
    });
    $("#n13").click(function(){
        $("#t14").show();
    });
	$("#y14").click(function(){
        $("#t15").show();
    });
	});