$(document).ready(function(){
    $("#y1").click(function(){
        $("#t1").hide();
    });
    $("#y1").click(function(){
        $("#t2").show();
    });
	$("#n1").click(function(){
        $("#t1").hide();
    });
    $("#n1").click(function(){
         $("#t2").show();
    });
	$("#m1").click(function(){
        $("#t1").hide();
    });
    $("#m1").click(function(){
         $("#t2").show();
    });
	$("#y2").click(function(){
        $("#t2").hide();
    });
    $("#y2").click(function(){
        $("#t4").show();
    });
	$("#n2").click(function(){
        $("#t2").hide();
    });
    $("#n2").click(function(){
         $("#t4").show();
    });
	$("#m2").click(function(){
        $("#t2").hide();
    });
    $("#m2").click(function(){
         $("#t4").show();
    });
	$("#y4").change(function(){
        $("#t4").hide();
    });
    $("#y4").change(function(){
        $("#t3").show();
    });
	$("#y4").change(function(){
        $("#t5").show();
    });
});


   
